# Generated by Django 3.0.7 on 2020-11-11 09:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCart',
            fields=[
                ('cartID', models.AutoField(primary_key=True, serialize=False)),
                ('shopID', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('productID', models.IntegerField()),
                ('productImage', models.TextField()),
                ('productPrice', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('price', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('shopID', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.BigIntegerField()),
                ('productImage', models.ImageField(blank=True, null=True, upload_to=api.models.product_path)),
            ],
            options={
                'db_table': 'Products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('covers', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user1',
            },
        ),
        migrations.CreateModel(
            name='UserRegistraton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserFirstName', models.CharField(max_length=100)),
                ('UserMiddleName', models.CharField(max_length=100)),
                ('UserLastName', models.CharField(max_length=100)),
                ('UserContactNo', models.CharField(max_length=100)),
                ('UserAddress', models.CharField(max_length=250)),
                ('UserEmail', models.EmailField(max_length=100)),
                ('UserPassword', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'UserRegistration',
            },
        ),
    ]
